version: "3.8"

services:
  site:
    image: vinicius-k/gerador-saudacoes:1.0
    ports:
      - "80:80"
    depends_on:
      - ms-pessoas-aleatorias
      - ms-saudacoes-aleatorias
    networks:
      - backend

  ms-pessoas-aleatorias:
    image: vinicius-k/ms-pessoas-aleatorias:1.0
    ports:
      - "8000:8000"
    networks:
      - backend

  ms-saudacoes-aleatorias:
    image: vinicius-k/ms-saudacoes-aleatorias:1.0
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend: {}
